### ISSUE TITLE
This repo contains 2 files called population_lecture2.ipynb in different locations

### ISSUE THREAD

**Issue by beckycardinali** [ligonteaching/EEP153_Materials#4]
- EEP153_Materials/population_lecture2.ipynb
- EEP153_Materials/Project1/population_lecture2.ipynb

**Comment by beckycardinali** [comment]
Good point!  Let's get rid of the one in the EEP153_Materials directory.

**Comment by ligon** [comment]
Addressed by commit [00e55be](https://github.com/ligonteaching/EEP153_Materials/commit/00e55be2bd6ccdd0d7c83b9f1642258cac781cab)
