### ISSUE TITLE
Problem reading google sheet data (Project 2)

### ISSUE THREAD

**Issue by kaitlinrh** [ligonteaching/EEP153_Materials#6]
I had a problem reading google sheet data (see images below). It turns out I was missing certain files (or they were misplaced) in my folders. After entering the password, I got a KeyError because my spreadsheet contained several different tabs, and the read_sheets function automatically grabbed the first tab (bypassing the step where I could specify which tab I wanted). The issue was resolved by manually moving the files to the correct location in my folders (see Professor Ligon for help).

<img width="801" alt="Screen_Shot_2022-03-01_at_9 30 46_PM" src="https://user-images.githubusercontent.com/49771828/156944771-34f81c5b-f12b-4fd7-a74c-7b546aa46cf3.png">
<img width="835" alt="Screen_Shot_2022-03-01_at_9 55 28_PM" src="https://user-images.githubusercontent.com/49771828/156944774-1a8065b8-f68a-489d-be69-f6ffaf1b8fa0.png">

**Comment by ligon** [comment]
This problem addressed by moving file with credentials to one's home directory.
