### ISSUE TITLE
Some issues with the code

### ISSUE THREAD

**Issue by Shelly1005** [ligonteaching/EEP153_Materials#9]
Dear Professor Ligon,

I encountered some difficulties while running the code for Project 3 and Project 4.

In the Project 3/prices.ipynb, I encountered an error "KeyError: "None of ['j'] are in the columns" when running the first cell. Upon further investigation, I found that the "j" column was missing from the "z" dataframe. I attempted to open the Google Spreadsheet to see if it could shed some light on the issue, but the URL returned an error message indicating that the file could not be found. It is possible that the Google Spreadsheet has been deleted or is otherwise inaccessible. In this case, the URL will not return any data and may show an error message.

In the EEP153_Materials/Project4/proof_of_concept.ipynb, I also encountered an issue with the Plot Demand Schedule. It displayed an "AssertionError: Something impossible happened" error message. To resolve this issue, I added a cell with the code "pbar=pbar.fillna(600)" and reran the cell that defined "pbar." This resolved the error. 

I would greatly appreciate it if you could take a look at these issues when you have a chance and provide any guidance or support. I understand that you are likely very busy and I appreciate your time.

Best regards,
Xiner Zhang

**Comment by ligon** [comment]
Xiner-

Could you please resubmit these as two different issues?  That will make tracking and resolving them simpler.
